### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gabmars** [Bogoyavlenskaya/urfu_python#1]
1. Не собирается топ каста. В поле stars записывается рейтинг.
2. Исключения обрабатываются только в нескольких местах, при изменении в dom могут возникнуть ошибки.
3. Блок details сохраняется в одну строку, будет не удобно использовать в дальнейшем.
В остальном все хорошо

**Comment by Bogoyavlenskaya** [comment]
> 1. Не собирается топ каста. В поле stars записывается рейтинг.
> 2. Исключения обрабатываются только в нескольких местах, при изменении в dom могут возникнуть ошибки.
> 3. Блок details сохраняется в одну строку, будет не удобно использовать в дальнейшем.
>    В остальном все хорошо

Исправлено

**Comment by gabmars** [comment]
Файл с кодом не читается

**Comment by Bogoyavlenskaya** [comment]
Запушила заново
